### ISSUE TITLE
exposing vscode-api

### ISSUE THREAD

**Issue by FalseProtagonist** [eclipse/sprotty-vscode#28]
If one attempts to use this extension, but use a different communication channel than the language server implementation,  one might want to use the vscode-api yourself in one's webview implementation. There's a good chance that I'm misunderstanding, but it seems like because the vscode-api is acquired in the sprotty-vscode-webview and not re-exported, it therefore cannot be used, since an attempt to acquire it "again" leads to an error (by design can only be acquired once).

**Comment by JanKoehnlein** [comment]
Looking at the code on master, the `vsCodeApi` is exported in `vscode-api.ts`. You should be able to reuse this in other modules in the webview's code via a simple import. Am I missing something?

**Comment by lforst** [comment]
It is actually very restricting to have the vscode API acquired this way in this package.

My use-case for example: I have a seprate script running within the webview besides the sprotty integration, that also needs to make use of the vscode API. Because the scripts are not bundled together the other script can't import the already acquired API.

I suggest you revisit this issue.

**Comment by spoenemann** [comment]
> I have a seprate script running within the webview besides the sprotty integration, that also needs to make use of the vscode API. Because the scripts are not bundled together the other script can't import the already acquired API.

@lforst how would you propose to solve that? If the scripts are not bundled together, how can they share a commonly acquired resource?

**Comment by lforst** [comment]
Just got the notification for this issue. Great change - thanks for taking the time to resolve this!
